In [44]:
import numpy as np
import pandas as pd

In [45]:
df = pd.read_csv("C:\\Users\\tusha\\OneDrive\\Documents\\important\\Datasets\\diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [46]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [47]:
df.duplicated().sum()

0

In [52]:
df['Glucose'] = np.where(df['Glucose'] == 0 , df['Glucose'].median(),df['Glucose'])
df['Insulin'] = np.where(df['Insulin'] == 0 , df['Insulin'].median(),df['Insulin'])


In [53]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72             35     30.5  33.6   
1            1     85.0             66             29     30.5  26.6   
2            8    183.0             64              0     30.5  23.3   
3            1     89.0             66             23     94.0  28.1   
4            0    137.0             40             35    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [54]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  121.656250      69.105469      20.536458   94.652344   
std       3.369578   30.438286      19.355807      15.952218  105.547598   
min       0.000000   44.000000       0.000000       0.000000   14.000000   
25%       1.000000   99.750000      62.000000       0.000000   30.500000   
50%       3.000000  117.000000      72.000000      23.000000   31.250000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    float64
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(4), int64(5)
memory usage: 54.1 KB


In [59]:
X = df.iloc[:,:8]
y = df.Outcome

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


In [65]:
from sklearn.model_selection import train_test_split

# Here we split the dataset into training and testing set
x_train , x_test , y_train, y_test = train_test_split(X , y , test_size=0.20 , random_state= 33 )

In [67]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10).fit(x_train,y_train)
y_pred = rf.predict(x_test)

In [69]:
y.value_counts()         # Here we that we have almost balance but not much

0    500
1    268
Name: Outcome, dtype: int64

In [70]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
print(confusion_matrix(y_test , y_pred))
print(accuracy_score(y_test , y_pred))
print(classification_report(y_test,y_pred))

[[91  8]
 [31 24]]
0.7467532467532467
              precision    recall  f1-score   support

           0       0.75      0.92      0.82        99
           1       0.75      0.44      0.55        55

    accuracy                           0.75       154
   macro avg       0.75      0.68      0.69       154
weighted avg       0.75      0.75      0.73       154



In [73]:
# Manual hyperparametert tuning
model = RandomForestClassifier(criterion='entropy', n_estimators=300 , 
                               max_features= 'sqrt',min_samples_leaf=10, 
                               random_state = 42).fit(x_train,y_train)

prediction = model.predict(x_test)
print(confusion_matrix(y_test,prediction))
print(accuracy_score(y_test,prediction))
print(classification_report(y_test,prediction))


[[89 10]
 [29 26]]
0.7467532467532467
              precision    recall  f1-score   support

           0       0.75      0.90      0.82        99
           1       0.72      0.47      0.57        55

    accuracy                           0.75       154
   macro avg       0.74      0.69      0.70       154
weighted avg       0.74      0.75      0.73       154



### Randomised Search Cross Validation

In [102]:
# Stratified search cross validation
from sklearn.model_selection import RandomizedSearchCV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(200,2000,10)]

# Number of feature consider at every split
max_features = ['auto','sqrt','log2']

# Maximum number of levels in trees
max_depth = [int(x) for x in np.linspace(10,1000,10)]

# Minimum number of samples required to split the node
min_samples_split = [1,3,4,5,7,9]

# Minimum number of samples required at each leaf node
min_samples_leaf = [1,2,4,6,8]

# creat the random_grid
random_grid = {'criterion':['entropy','gini'],
               'n_estimators' : n_estimators,
               'max_features' : max_features,
               'max_depth' : max_depth,
               'min_samples_split' : min_samples_split,
               'min_samples_leaf': min_samples_leaf
              }

print(random_grid)

{'criterion': ['entropy', 'gini'], 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [1, 3, 4, 5, 7, 9], 'min_samples_leaf': [1, 2, 4, 6, 8]}


In [103]:
rf = RandomForestClassifier()
rf_randomcv = RandomizedSearchCV(estimator=rf,param_distributions=random_grid,
                                 n_iter = 100 , cv = 3 , verbose =2,
                                 random_state=100 , n_jobs=-1)

rf_randomcv.fit(x_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


C:\Users\tusha\AppData\Roaming\Python\Python310\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
51 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
51 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\tusha\AppData\Roaming\Python\Python310\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\tusha\AppData\Roaming\Python\Python310\site-packages\sklearn\ensemble\_forest.py", line 476, in fit
    trees = Parallel(
  File "C:\Users\tusha\AppData\Roaming\Python\Python310\site-packages\joblib\parallel.py", line 1043, in __call__
    if self.dispat

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [1, 3, 4, 5, 7, 9],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [107]:
rf_randomcv.best_params_

{'n_estimators': 400,
 'min_samples_split': 5,
 'min_samples_leaf': 8,
 'max_features': 'log2',
 'max_depth': 340,
 'criterion': 'gini'}

In [105]:
rf_randomcv.best_estimator_

RandomForestClassifier(max_depth=340, max_features='log2', min_samples_leaf=8,
                       min_samples_split=5, n_estimators=400)

In [108]:
model = RandomForestClassifier(criterion='gini', max_depth=340, min_samples_split=5,
                       n_estimators=400 , max_features='log2').fit(x_train,y_train)
prediction = model.predict(x_test)
print(confusion_matrix(y_test,prediction))
print(accuracy_score(y_test,prediction))
print(classification_report(y_test,prediction))


[[87 12]
 [23 32]]
0.7727272727272727
              precision    recall  f1-score   support

           0       0.79      0.88      0.83        99
           1       0.73      0.58      0.65        55

    accuracy                           0.77       154
   macro avg       0.76      0.73      0.74       154
weighted avg       0.77      0.77      0.77       154



- In Randomised seach cv we actually find out the best possible region where our model will be performed well. Later on we use Gridsearch CV by using this region ro find out best possible hyper-parameters.

### Grid Search CV

In [109]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion' : [rf_randomcv.best_params_['criterion']],
              'max_features' : [rf_randomcv.best_params_['max_features']],
              'max_depth' : [rf_randomcv.best_params_['max_depth']],
              'min_samples_leaf' : [rf_randomcv.best_params_['min_samples_leaf'],
                                   rf_randomcv.best_params_['min_samples_leaf']+2,
                                   rf_randomcv.best_params_['min_samples_leaf']+4],
              'min_samples_split' : [ rf_randomcv.best_params_['min_samples_split']-2,
                                     rf_randomcv.best_params_['min_samples_split']-1,
                                     rf_randomcv.best_params_['min_samples_split'],
                                     rf_randomcv.best_params_['min_samples_split']+1,
                                     rf_randomcv.best_params_['min_samples_split']+2],
              'n_estimators' : [rf_randomcv.best_params_['n_estimators']-400,
                                rf_randomcv.best_params_['n_estimators']-300,
                                rf_randomcv.best_params_['n_estimators']-200,
                                rf_randomcv.best_params_['n_estimators'],
                                rf_randomcv.best_params_['n_estimators']+200,
                                rf_randomcv.best_params_['n_estimators']+300
                                ]
             }
print(param_grid)

{'criterion': ['gini'], 'max_features': ['log2'], 'max_depth': [340], 'min_samples_leaf': [8, 10, 12], 'min_samples_split': [3, 4, 5, 6, 7], 'n_estimators': [0, 100, 200, 400, 600, 700]}


In [110]:
rf_gridSeachcv = GridSearchCV(estimator=rf , param_grid= param_grid , cv = 10 , n_jobs=-1,verbose=2).fit(x_train,y_train)
prediction = rf_gridSeachcv.predict(x_test)

Fitting 10 folds for each of 90 candidates, totalling 900 fits


C:\Users\tusha\AppData\Roaming\Python\Python310\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
150 fits failed out of a total of 900.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
150 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\tusha\AppData\Roaming\Python\Python310\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\tusha\AppData\Roaming\Python\Python310\site-packages\sklearn\ensemble\_forest.py", line 396, in fit
    self._validate_estimator()
  File "C:\Users\tusha\AppData\Roaming\Python\Python310\site-packages\sklearn\ensemble\_base.py", line 143, in _validate_

In [111]:
print(confusion_matrix(y_test,prediction))
print(accuracy_score(y_test,prediction))
print(classification_report(y_test,prediction))

[[88 11]
 [27 28]]
0.7532467532467533
              precision    recall  f1-score   support

           0       0.77      0.89      0.82        99
           1       0.72      0.51      0.60        55

    accuracy                           0.75       154
   macro avg       0.74      0.70      0.71       154
weighted avg       0.75      0.75      0.74       154



In [112]:
rf_gridSeachcv.best_params_

{'criterion': 'gini',
 'max_depth': 340,
 'max_features': 'log2',
 'min_samples_leaf': 10,
 'min_samples_split': 6,
 'n_estimators': 700}

In [113]:
rf_gridSeachcv.best_estimator_

RandomForestClassifier(max_depth=340, max_features='log2', min_samples_leaf=10,
                       min_samples_split=6, n_estimators=700)

In [115]:
model = RandomForestClassifier(criterion= 'gini' , max_depth=340,
                               max_features= 'log2',min_samples_leaf=10,
                               min_samples_split = 6, n_estimators= 700).fit(x_train,y_train)
prediction = model.predict(x_test)
print(confusion_matrix(y_test,prediction))
print(accuracy_score(y_test,prediction))
print(classification_report(y_test,prediction))

[[87 12]
 [27 28]]
0.7467532467532467
              precision    recall  f1-score   support

           0       0.76      0.88      0.82        99
           1       0.70      0.51      0.59        55

    accuracy                           0.75       154
   macro avg       0.73      0.69      0.70       154
weighted avg       0.74      0.75      0.74       154

